In [1]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer


In [2]:
text=["The quick brown fox jumped over the lazy dog.",
     "The dog.", "The fox"]

In [3]:
vectorize=TfidfVectorizer()
vectorize.fit(text)


TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [4]:
print(vectorize.vocabulary_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}


In [5]:
print(vectorize.idf_)

[1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]


In [6]:
vector=vectorize.transform([text[0]])

In [7]:
print(vector.shape)

(1, 8)


In [8]:
print(vector.toarray)

<bound method _cs_matrix.toarray of <1x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>>


In [9]:
from keras.preprocessing.text import Tokenizer


In [10]:
docs=['Well done!','Good work','Great effort','nice work','Excellent!']

In [11]:
t=Tokenizer()
t.fit_on_texts(docs)

In [12]:
print(t.word_counts)

OrderedDict([('well', 1), ('done', 1), ('good', 1), ('work', 2), ('great', 1), ('effort', 1), ('nice', 1), ('excellent', 1)])


In [13]:
print(t.document_count)

5


In [14]:
t.word_index

{'work': 1,
 'well': 2,
 'done': 3,
 'good': 4,
 'great': 5,
 'effort': 6,
 'nice': 7,
 'excellent': 8}

In [15]:
t.word_docs

defaultdict(int,
            {'done': 1,
             'well': 1,
             'work': 2,
             'good': 1,
             'effort': 1,
             'great': 1,
             'nice': 1,
             'excellent': 1})

In [16]:
encoded_dcs=t.texts_to_matrix(docs, mode='count')
print(encoded_dcs)

[[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
